[package]
name = "serial"
version = "0.2.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.97"
nusb = "0.1.13"
tokio = { version = "1.44.1", features = ["macros", "rt", "time"] }
