body:
  - type: textarea
    attributes:
      label: What's your question?
      description: |
        Before asking, please check the [FAQ](https://efforg.github.io/rayhunter/faq.html)
        and search existing discussions. If you're reporting a bug, please open an issue instead.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I have read [CONTRIBUTING.md](https://github.com/EFForg/rayhunter/blob/main/CONTRIBUTING.md)
          required: true
        - label: No generative AI (including LLMs) tools were used to write this post.
          required: true
