// @generated by rayhunter-deps generate -- do not edit

use rayhunter::Device;

#[allow(dead_code)]
pub struct DeviceCapabilities {
    pub battery_monitoring: bool,
    pub battery_notifications: bool,
    pub wifi_client_mode: bool,
}

pub fn capabilities_for(device: &Device) -> DeviceCapabilities {
    match device {
        Device::Orbic => DeviceCapabilities {
            battery_monitoring: true,
            battery_notifications: true,
            wifi_client_mode: true,
        },
        Device::Pinephone => DeviceCapabilities {
            battery_monitoring: false,
            battery_notifications: false,
            wifi_client_mode: false,
        },
        Device::Tmobile => DeviceCapabilities {
            battery_monitoring: true,
            battery_notifications: true,
            wifi_client_mode: false,
        },
        Device::Tplink => DeviceCapabilities {
            battery_monitoring: true,
            battery_notifications: true,
            wifi_client_mode: false,
        },
        Device::Uz801 => DeviceCapabilities {
            battery_monitoring: false,
            battery_notifications: false,
            wifi_client_mode: false,
        },
        Device::Wingtech => DeviceCapabilities {
            battery_monitoring: true,
            battery_notifications: true,
            wifi_client_mode: false,
        },
    }
}
