name: Check and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose
    - name: Check (device-tplink-m7350)
      run: cargo check --verbose --no-default-features --features=device-tplink-m7350
    - name: Run tests
      run: cargo test --verbose
